import 'package:kenviz/domain/entities/test_item_master.dart';

/// 検査カテゴリマスタ (初期データ)
const defaultCategories = [
  TestCategory(
    id: 'body',
    name: '身体計測',
    displayOrder: 1,
    iconName: 'straighten',
  ),
  TestCategory(id: 'bp', name: '血圧', displayOrder: 2, iconName: 'favorite'),
  TestCategory(
    id: 'blood',
    name: '血液一般',
    displayOrder: 3,
    iconName: 'water_drop',
  ),
  TestCategory(id: 'lipid', name: '脂質', displayOrder: 4, iconName: 'science'),
  TestCategory(id: 'sugar', name: '糖代謝', displayOrder: 5, iconName: 'cookie'),
  TestCategory(
    id: 'liver',
    name: '肝機能',
    displayOrder: 6,
    iconName: 'local_hospital',
  ),
  TestCategory(id: 'kidney', name: '腎機能', displayOrder: 7, iconName: 'water'),
  TestCategory(id: 'urine', name: '尿検査', displayOrder: 8, iconName: 'biotech'),
  TestCategory(id: 'eye', name: '眼科', displayOrder: 9, iconName: 'visibility'),
  TestCategory(
    id: 'hearing',
    name: '聴力',
    displayOrder: 10,
    iconName: 'hearing',
  ),
  TestCategory(
    id: 'other',
    name: 'その他',
    displayOrder: 11,
    iconName: 'more_horiz',
  ),
];

/// 検査項目マスタ (初期データ)
///
/// 基準値は「特定健康診査」の基準を初期値とする。
/// 性別・年齢による差異は将来対応。
const defaultTestItems = [
  // ── 身体計測 ──
  TestItemMaster(
    id: 'HEIGHT',
    categoryId: 'body',
    standardName: '身長',
    aliases: ['身長(cm)'],
    unit: 'cm',
    defaultRefLow: 100,
    defaultRefHigh: 200,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'WEIGHT',
    categoryId: 'body',
    standardName: '体重',
    aliases: ['体重(kg)'],
    unit: 'kg',
    defaultRefLow: 30,
    defaultRefHigh: 150,
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'BMI',
    categoryId: 'body',
    standardName: 'BMI',
    aliases: ['BMI', '体格指数'],
    defaultRefLow: 18.5,
    defaultRefHigh: 24.9,
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'WAIST',
    categoryId: 'body',
    standardName: '腹囲',
    aliases: ['腹囲(cm)', 'ウエスト', '腹部周囲径'],
    unit: 'cm',
    defaultRefHigh: 85,
    displayOrder: 4,
  ),
  TestItemMaster(
    id: 'BODY_FAT',
    categoryId: 'body',
    standardName: '体脂肪率',
    aliases: ['体脂肪', '体脂肪率(%)'],
    unit: '%',
    displayOrder: 5,
  ),

  // ── 血圧 ──
  TestItemMaster(
    id: 'BP_SYS',
    categoryId: 'bp',
    standardName: '収縮期血圧',
    aliases: ['最高血圧', '最高', '血圧(上)', '血圧(収縮期)', 'SBP', '収縮期'],
    unit: 'mmHg',
    defaultRefHigh: 129,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'BP_DIA',
    categoryId: 'bp',
    standardName: '拡張期血圧',
    aliases: ['最低血圧', '最低', '血圧(下)', '血圧(拡張期)', 'DBP', '拡張期'],
    unit: 'mmHg',
    defaultRefHigh: 84,
    displayOrder: 2,
  ),

  // ── 眼科 ──
  TestItemMaster(
    id: 'VISION_R',
    categoryId: 'eye',
    standardName: '視力(右)',
    aliases: ['裸眼視力(右)', '矯正視力(右)', '右視力'],
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'VISION_L',
    categoryId: 'eye',
    standardName: '視力(左)',
    aliases: ['裸眼視力(左)', '矯正視力(左)', '左視力'],
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'IOP_R',
    categoryId: 'eye',
    standardName: '眼圧(右)',
    aliases: ['眼圧右', '眼圧 右'],
    unit: 'mmHg',
    defaultRefLow: 10,
    defaultRefHigh: 21,
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'IOP_L',
    categoryId: 'eye',
    standardName: '眼圧(左)',
    aliases: ['眼圧左', '眼圧 左'],
    unit: 'mmHg',
    defaultRefLow: 10,
    defaultRefHigh: 21,
    displayOrder: 4,
  ),

  // ── 血液一般 ──
  TestItemMaster(
    id: 'RBC',
    categoryId: 'blood',
    standardName: '赤血球',
    aliases: ['赤血球数', 'RBC'],
    unit: '万/μL',
    defaultRefLow: 400,
    defaultRefHigh: 539,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'WBC',
    categoryId: 'blood',
    standardName: '白血球',
    aliases: ['白血球数', 'WBC'],
    unit: '/μL',
    defaultRefLow: 3500,
    defaultRefHigh: 9000,
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'HB',
    categoryId: 'blood',
    standardName: 'ヘモグロビン',
    aliases: ['Hb', 'Hgb', '血色素量', '血色素'],
    unit: 'g/dL',
    defaultRefLow: 13.0,
    defaultRefHigh: 17.0,
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'HCT',
    categoryId: 'blood',
    standardName: 'ヘマトクリット',
    aliases: ['Ht', 'Hct'],
    unit: '%',
    defaultRefLow: 39.0,
    defaultRefHigh: 52.0,
    displayOrder: 4,
  ),
  TestItemMaster(
    id: 'PLT',
    categoryId: 'blood',
    standardName: '血小板',
    aliases: ['血小板数', 'PLT', 'Plt'],
    unit: '万/μL',
    defaultRefLow: 15.0,
    defaultRefHigh: 35.0,
    displayOrder: 5,
  ),
  TestItemMaster(
    id: 'MCV',
    categoryId: 'blood',
    standardName: 'MCV',
    aliases: ['平均赤血球容積'],
    unit: 'fL',
    defaultRefLow: 80,
    defaultRefHigh: 100,
    displayOrder: 6,
  ),
  TestItemMaster(
    id: 'MCH',
    categoryId: 'blood',
    standardName: 'MCH',
    aliases: ['平均赤血球血色素量'],
    unit: 'pg',
    defaultRefLow: 26,
    defaultRefHigh: 34,
    displayOrder: 7,
  ),
  TestItemMaster(
    id: 'MCHC',
    categoryId: 'blood',
    standardName: 'MCHC',
    aliases: ['平均赤血球血色素濃度'],
    unit: '%',
    defaultRefLow: 32.0,
    defaultRefHigh: 36.0,
    displayOrder: 8,
  ),
  TestItemMaster(
    id: 'RETIC',
    categoryId: 'blood',
    standardName: '網状赤血球',
    aliases: ['網赤血球', 'Ret', '網状赤血球数'],
    unit: '‰',
    defaultRefLow: 4,
    defaultRefHigh: 20,
    displayOrder: 9,
  ),
  TestItemMaster(
    id: 'FE',
    categoryId: 'blood',
    standardName: '血清鉄',
    aliases: ['Fe', '鉄', '血清鉄(Fe)'],
    unit: 'μg/dL',
    defaultRefLow: 50,
    defaultRefHigh: 180,
    displayOrder: 10,
  ),

  // ── 脂質 ──
  TestItemMaster(
    id: 'LDL_C',
    categoryId: 'lipid',
    standardName: 'LDL-コレステロール',
    aliases: ['LDL-C', 'LDLコレステロール', 'LDL', '悪玉コレステロール', 'LDL-Cho'],
    unit: 'mg/dL',
    defaultRefLow: 70,
    defaultRefHigh: 139,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'HDL_C',
    categoryId: 'lipid',
    standardName: 'HDL-コレステロール',
    aliases: ['HDL-C', 'HDLコレステロール', 'HDL', '善玉コレステロール', 'HDL-Cho'],
    unit: 'mg/dL',
    defaultRefLow: 40,
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'TG',
    categoryId: 'lipid',
    standardName: '中性脂肪',
    aliases: ['TG', 'トリグリセリド', 'トリグリセライド', '中性脂肪(TG)'],
    unit: 'mg/dL',
    defaultRefLow: 30,
    defaultRefHigh: 149,
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'TC',
    categoryId: 'lipid',
    standardName: '総コレステロール',
    aliases: ['T-Cho', 'TC', 'T-C'],
    unit: 'mg/dL',
    defaultRefLow: 150,
    defaultRefHigh: 219,
    displayOrder: 4,
  ),

  // ── 糖代謝 ──
  TestItemMaster(
    id: 'FPG',
    categoryId: 'sugar',
    standardName: '空腹時血糖',
    aliases: ['FPG', '血糖(空腹時)', 'グルコース', '血糖', 'FBS'],
    unit: 'mg/dL',
    defaultRefLow: 70,
    defaultRefHigh: 99,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'HBA1C',
    categoryId: 'sugar',
    standardName: 'HbA1c',
    aliases: ['HbA1c(NGSP)', 'ヘモグロビンA1c', 'HbA1C', 'HBA1C'],
    unit: '%',
    defaultRefLow: 4.6,
    defaultRefHigh: 5.9,
    displayOrder: 2,
  ),

  // ── 肝機能 ──
  TestItemMaster(
    id: 'AST',
    categoryId: 'liver',
    standardName: 'AST',
    aliases: ['AST(GOT)', 'GOT', 'AST(GOT)'],
    unit: 'U/L',
    defaultRefLow: 10,
    defaultRefHigh: 30,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'ALT',
    categoryId: 'liver',
    standardName: 'ALT',
    aliases: ['ALT(GPT)', 'GPT', 'ALT(GPT)'],
    unit: 'U/L',
    defaultRefLow: 6,
    defaultRefHigh: 30,
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'GGT',
    categoryId: 'liver',
    standardName: 'γ-GTP',
    aliases: ['γGTP', 'ガンマGTP', 'γ-GT', 'GGT', 'γ-GTP', 'r-GTP'],
    unit: 'U/L',
    defaultRefHigh: 50,
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'ALP',
    categoryId: 'liver',
    standardName: 'ALP',
    aliases: ['ALP', 'アルカリフォスファターゼ'],
    unit: 'U/L',
    defaultRefLow: 38,
    defaultRefHigh: 113,
    displayOrder: 4,
  ),
  TestItemMaster(
    id: 'TBIL',
    categoryId: 'liver',
    standardName: '総ビリルビン',
    aliases: ['T-Bil', 'T-BIL', 'ビリルビン'],
    unit: 'mg/dL',
    defaultRefLow: 0.2,
    defaultRefHigh: 1.2,
    displayOrder: 5,
  ),
  TestItemMaster(
    id: 'TP',
    categoryId: 'liver',
    standardName: '総蛋白',
    aliases: ['TP', '総タンパク', '血清総蛋白'],
    unit: 'g/dL',
    defaultRefLow: 6.5,
    defaultRefHigh: 8.0,
    displayOrder: 6,
  ),
  TestItemMaster(
    id: 'ALB',
    categoryId: 'liver',
    standardName: 'アルブミン',
    aliases: ['Alb', 'ALB'],
    unit: 'g/dL',
    defaultRefLow: 3.8,
    defaultRefHigh: 5.3,
    displayOrder: 7,
  ),
  TestItemMaster(
    id: 'LDH',
    categoryId: 'liver',
    standardName: 'LDH',
    aliases: ['LD', '乳酸脱水素酵素'],
    unit: 'U/L',
    defaultRefLow: 120,
    defaultRefHigh: 240,
    displayOrder: 8,
  ),

  // ── 腎機能 ──
  TestItemMaster(
    id: 'CRE',
    categoryId: 'kidney',
    standardName: 'クレアチニン',
    aliases: ['Cr', 'CRE', 'Cre', 'クレアチニン(Cr)'],
    unit: 'mg/dL',
    defaultRefLow: 0.6,
    defaultRefHigh: 1.1,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'EGFR',
    categoryId: 'kidney',
    standardName: 'eGFR',
    aliases: ['推算GFR', 'eGFR'],
    unit: 'mL/min/1.73m2',
    defaultRefLow: 60,
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'BUN',
    categoryId: 'kidney',
    standardName: 'BUN',
    aliases: ['尿素窒素', 'UN', 'BUN'],
    unit: 'mg/dL',
    defaultRefLow: 8,
    defaultRefHigh: 20,
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'UA',
    categoryId: 'kidney',
    standardName: '尿酸',
    aliases: ['UA', '尿酸(UA)'],
    unit: 'mg/dL',
    defaultRefLow: 2.1,
    defaultRefHigh: 7.0,
    displayOrder: 4,
  ),

  // ── 尿検査 ──
  TestItemMaster(
    id: 'U_GLU',
    categoryId: 'urine',
    standardName: '尿糖',
    aliases: ['尿糖(定性)'],
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'U_PRO',
    categoryId: 'urine',
    standardName: '尿蛋白',
    aliases: ['尿蛋白(定性)', '尿たんぱく'],
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'U_OB',
    categoryId: 'urine',
    standardName: '尿潜血',
    aliases: ['尿潜血(定性)'],
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'U_SG',
    categoryId: 'urine',
    standardName: '尿比重',
    aliases: ['比重'],
    defaultRefLow: 1.006,
    defaultRefHigh: 1.030,
    displayOrder: 4,
  ),
  TestItemMaster(
    id: 'U_PH',
    categoryId: 'urine',
    standardName: '尿PH',
    aliases: ['尿pH', 'PH'],
    defaultRefLow: 5.0,
    defaultRefHigh: 7.5,
    displayOrder: 5,
  ),
  TestItemMaster(
    id: 'U_URO',
    categoryId: 'urine',
    standardName: '尿ウロビリノーゲン',
    aliases: ['ウロビリノーゲン'],
    displayOrder: 6,
  ),
  TestItemMaster(
    id: 'U_RBC',
    categoryId: 'urine',
    standardName: '尿沈渣赤血球',
    aliases: ['尿沈査 赤血球', '尿沈渣 赤血球', '尿沈査赤血球', '尿中赤血球'],
    displayOrder: 7,
  ),
  TestItemMaster(
    id: 'U_WBC',
    categoryId: 'urine',
    standardName: '尿沈渣白血球',
    aliases: ['尿沈査 白血球', '尿沈渣 白血球', '尿沈査白血球', '尿中白血球'],
    displayOrder: 8,
  ),

  // ── その他 ──
  TestItemMaster(
    id: 'CRP',
    categoryId: 'other',
    standardName: 'CRP',
    aliases: ['C反応性蛋白', 'C反応性タンパク'],
    unit: 'mg/dL',
    defaultRefHigh: 0.3,
    displayOrder: 1,
  ),
  TestItemMaster(
    id: 'RF',
    categoryId: 'other',
    standardName: 'RF',
    aliases: ['リウマチ因子', 'RA', 'リウマトイド因子'],
    unit: 'IU/mL',
    defaultRefHigh: 15,
    displayOrder: 2,
  ),
  TestItemMaster(
    id: 'PSA',
    categoryId: 'other',
    standardName: 'PSA',
    aliases: ['前立腺特異抗原'],
    unit: 'ng/mL',
    defaultRefHigh: 4.0,
    displayOrder: 3,
  ),
  TestItemMaster(
    id: 'HEART_RATE',
    categoryId: 'bp',
    standardName: '心拍数',
    aliases: ['脈拍', '脈拍数', 'HR'],
    unit: '回/分',
    defaultRefLow: 60,
    defaultRefHigh: 100,
    displayOrder: 3,
  ),
];
